export const LANGUAGES = {
  EN: 'en',
  ES: 'es',
  NL: 'nl',
}

export const SPORTS = {
  FOOTBALL: 'FOOTBALL',
  // VOLLEYBALL: 'VOLLEYBALL',
  BEACH_VOLLEYBALL: 'BEACH_VOLLEYBALL',
  TENNIS: 'TENNIS',
  TABLE_TENNIS: 'TABLE_TENNIS',
  ABSOLUTE_FRISBEE: 'ABSOLUTE_FRISBEE',
  BASKETBALL: 'BASKETBALL',
  BADMINTON: 'BADMINTON',
}

export const ACTIVITY_STATUSES = {
  ACTIVE: 'ACTIVE',
  CANCELED: 'CANCELED',
  FINISHED: 'FINISHED',
  DELETED: 'DELETED',
}

export const NOTIFICATION_TYPES = {
  NEW_ACTIVITY: 'NEW_ACTIVITY', // Not sure if we need this
  ACTIVITY_CANCELED: 'ACTIVITY_CANCELED',
  ACTIVITY_RECREATED: 'ACTIVITY_RECREATED',
  ATTENDEE_ADDED: 'ATTENDEE_ADDED',
  ATTENDEE_REMOVED: 'ATTENDEE_REMOVED',
  NEW_MESSAGE: 'NEW_MESSAGE',
}
